window.WEDDING_SITE_DATA = {
  coupleName: "배형범 · 박수빈",
  weddingDate: "2026-10-25T11:00:00+09:00",
  shareTitle: "배형범 · 박수빈 결혼합니다",
  shareDescription: "2026년 10월 25일 일요일 오전 11시, 엔팰리스웨딩컨벤션",
  shareImage: "./Image/optimized/pink-flower-window-couple.webp",
  petals: {
    enabled: true,
    heroCount: 8,
    sectionCount: 3,
  },
  welcomeMessages: [
    "소중한 발걸음을 기다립니다.",
    "오늘도 저희의 초대장을 열어주셔서 감사합니다.",
    "축복해 주실 마음을 생각하며 기다리고 있습니다.",
    "함께해 주시는 마음이 가장 큰 선물입니다.",
    "좋은 날, 좋은 마음으로 뵙겠습니다.",
  ],
  venue: {
    name: "엔팰리스웨딩컨벤션",
    address: "경기 평택시 경기대로 721",
    kakaoMapUrl: "https://map.kakao.com/link/search/엔팰리스웨딩컨벤션",
    naverMapUrl: "https://map.naver.com/p/search/엔팰리스웨딩컨벤션",
  },
  albumImages: [
    { src: "./Image/optimized/pink-flower-window-couple.webp", alt: "분홍 꽃과 창가에 선 신랑 신부" },
    { src: "./Image/optimized/blush-dress-sunlight-couple.webp", alt: "햇살 아래 연분홍 드레스의 신부와 신랑" },
    { src: "./Image/optimized/confetti-dance-wide.webp", alt: "꽃잎 사이에서 춤추는 신랑 신부" },
    { src: "./Image/optimized/confetti-holding-hands.webp", alt: "꽃잎 사이에서 손을 맞잡은 두 사람" },
    { src: "./Image/optimized/confetti-laughing-couple.webp", alt: "꽃잎 아래 함께 웃는 신랑 신부" },
    { src: "./Image/optimized/yellow-bouquet-embrace.webp", alt: "노란 부케를 들고 포옹한 두 사람" },
    { src: "./Image/optimized/yellow-bouquet-shoulder-pose.webp", alt: "노란 부케를 들고 어깨에 기댄 신부" },
    { src: "./Image/optimized/yellow-bouquet-looking-down.webp", alt: "노란 부케를 함께 바라보는 두 사람" },
    { src: "./Image/optimized/yellow-bouquet-formal-pose.webp", alt: "노란 부케와 나란히 선 신랑 신부" },
    { src: "./Image/optimized/tall-cake-playful-forks.webp", alt: "커다란 웨딩 케이크 옆 장난스러운 두 사람" },
    { src: "./Image/optimized/tall-cake-smiling-forks.webp", alt: "웨딩 케이크를 사이에 두고 웃는 두 사람" },
    { src: "./Image/optimized/candle-table-bride.webp", alt: "촛불 테이블 앞에 선 신부" },
    { src: "./Image/optimized/candle-table-couple.webp", alt: "촛불 테이블 앞에서 마주 본 신랑 신부" },
    { src: "./Image/optimized/doorway-peekaboo-couple.webp", alt: "문 뒤에서 얼굴을 내민 신랑 신부" },
    { src: "./Image/optimized/brick-door-leaning-couple.webp", alt: "꽃 장식 벽돌문 앞에 기대 선 두 사람" },
    { src: "./Image/optimized/blush-dress-forehead-kiss.webp", alt: "연분홍 드레스와 이마를 맞댄 두 사람" },
    { src: "./Image/optimized/blush-dress-near-kiss.webp", alt: "햇살 아래 입맞춤을 앞둔 두 사람" },
    { src: "./Image/optimized/blush-dress-gazing.webp", alt: "연분홍 드레스를 입고 마주 보는 두 사람" },
    { src: "./Image/optimized/pink-table-shoulder-rest.webp", alt: "분홍 꽃 테이블에서 어깨에 기댄 신부" },
    { src: "./Image/optimized/pink-table-close-couple.webp", alt: "분홍 꽃 테이블에 다정히 앉은 두 사람" },
    { src: "./Image/optimized/pink-table-smiling-couple.webp", alt: "분홍 꽃 테이블에서 환하게 웃는 두 사람" },
    { src: "./Image/optimized/pink-table-gentle-smiles.webp", alt: "분홍 꽃 테이블에서 미소 짓는 신랑 신부" },
    { src: "./Image/optimized/pink-flower-window-seated.webp", alt: "분홍 꽃이 가득한 창가에 앉은 두 사람" },
    { src: "./Image/optimized/blue-flower-garden-couple.webp", alt: "푸른 꽃 정원에 함께 앉은 신랑 신부" },
    { src: "./Image/optimized/green-garden-formal-couple.webp", alt: "초록 정원 앞에 나란히 선 두 사람" },
    { src: "./Image/optimized/pink-table-bride-portrait.webp", alt: "분홍 꽃 테이블에 앉은 신부" },
    { src: "./Image/optimized/veil-wrapped-bride-portrait.webp", alt: "베일을 감싼 신부의 클로즈업" },
    { src: "./Image/optimized/veil-table-near-kiss.webp", alt: "베일 아래 입맞춤을 앞둔 두 사람" },
    { src: "./Image/optimized/blue-flower-playful-couple.webp", alt: "푸른 꽃밭에서 장난치는 신랑 신부" },
    { src: "./Image/optimized/yellow-bouquet-wall-couple.webp", alt: "노란 부케를 들고 벽 앞에 선 두 사람" },
  ],
  accounts: [
    {
      side: "신랑측",
      name: "배형범",
      bank: "국민은행",
      number: "123456-78-901234",
      holder: "배형범",
    },
    {
      side: "신부측",
      name: "박수빈",
      bank: "신한은행",
      number: "110-123-456789",
      holder: "박수빈",
    },
  ],
};
