create table if not exists public.guestbook (
  id bigint generated by default as identity primary key,
  name text not null,
  attendance text not null default '참석 예정',
  message text not null,
  edit_code_hash text,
  owner_token_hash text,
  created_at timestamptz not null default now()
);

create extension if not exists pgcrypto;

drop function if exists public.create_guestbook_entry(text, text, text, text);
drop function if exists public.update_guestbook_entry(bigint, text, text, text, text);
drop function if exists public.delete_guestbook_entry(bigint, text);
drop function if exists public.list_guestbook_entries(text);
drop function if exists public.admin_update_guestbook_entry(bigint, text, text, text);
drop function if exists public.admin_delete_guestbook_entry(bigint);

alter table public.guestbook
  add column if not exists edit_code_hash text;

alter table public.guestbook
  add column if not exists owner_token_hash text;

update public.guestbook
set edit_code_hash = crypt(gen_random_uuid()::text, gen_salt('bf'))
where edit_code_hash is null;

alter table public.guestbook
  alter column edit_code_hash drop not null;

update public.guestbook
set owner_token_hash = crypt(gen_random_uuid()::text, gen_salt('bf'))
where owner_token_hash is null;

alter table public.guestbook
  alter column owner_token_hash set not null;

do $$
declare
  constraint_record record;
begin
  for constraint_record in
    select conname
    from pg_constraint
    where conrelid = 'public.guestbook'::regclass
      and contype = 'c'
  loop
    execute format('alter table public.guestbook drop constraint if exists %I', constraint_record.conname);
  end loop;
end $$;

alter table public.guestbook
  add constraint guestbook_name_length check (char_length(name) between 1 and 20),
  add constraint guestbook_attendance_valid check (attendance in ('참석 예정', '불참', '미정')),
  add constraint guestbook_message_length check (char_length(message) between 1 and 300);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  created_at timestamptz not null default now()
);

alter table public.guestbook enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists "Anyone can read guestbook" on public.guestbook;
drop policy if exists "Anyone can write guestbook" on public.guestbook;
drop policy if exists "Admins can update guestbook" on public.guestbook;
drop policy if exists "Admins can delete guestbook" on public.guestbook;
drop policy if exists "Admins can read admin users" on public.admin_users;

create policy "Anyone can read guestbook"
on public.guestbook
for select
to anon, authenticated
using (true);

create policy "Admins can update guestbook"
on public.guestbook
for update
to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = auth.uid()
  )
  and char_length(name) between 1 and 20
  and attendance in ('참석 예정', '불참', '미정')
  and char_length(message) between 1 and 300
);

create policy "Admins can delete guestbook"
on public.guestbook
for delete
to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

create policy "Admins can read admin users"
on public.admin_users
for select
to authenticated
using (user_id = auth.uid());

create index if not exists guestbook_created_at_idx
on public.guestbook (created_at desc);

create or replace function public.list_guestbook_entries(
  p_owner_token text
)
returns table (
  id bigint,
  name text,
  attendance text,
  message text,
  created_at timestamptz,
  can_edit boolean
)
language sql
security definer
set search_path = public, extensions, pg_temp
as $$
  select
    guestbook.id,
    guestbook.name,
    guestbook.attendance,
    guestbook.message,
    guestbook.created_at,
    guestbook.owner_token_hash = crypt(p_owner_token, guestbook.owner_token_hash) as can_edit
  from public.guestbook
  order by guestbook.created_at desc
  limit 50;
$$;

create or replace function public.create_guestbook_entry(
  p_name text,
  p_attendance text,
  p_message text,
  p_owner_token text
)
returns bigint
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  new_id bigint;
begin
  if char_length(p_name) not between 1 and 20 then
    raise exception 'invalid name';
  end if;

  if p_attendance not in ('참석 예정', '불참', '미정') then
    raise exception 'invalid attendance';
  end if;

  if char_length(p_message) not between 1 and 300 then
    raise exception 'invalid message';
  end if;

  if char_length(p_owner_token) not between 12 and 200 then
    raise exception 'invalid owner token';
  end if;

  insert into public.guestbook (name, attendance, message, owner_token_hash)
  values (p_name, p_attendance, p_message, crypt(p_owner_token, gen_salt('bf')))
  returning id into new_id;

  return new_id;
end;
$$;

create or replace function public.update_guestbook_entry(
  p_id bigint,
  p_name text,
  p_attendance text,
  p_message text,
  p_owner_token text
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
begin
  if char_length(p_name) not between 1 and 20 then
    return false;
  end if;

  if p_attendance not in ('참석 예정', '불참', '미정') then
    return false;
  end if;

  if char_length(p_message) not between 1 and 300 then
    return false;
  end if;

  update public.guestbook
  set
    name = p_name,
    attendance = p_attendance,
    message = p_message
  where id = p_id
    and owner_token_hash = crypt(p_owner_token, owner_token_hash);

  return found;
end;
$$;

create or replace function public.delete_guestbook_entry(
  p_id bigint,
  p_owner_token text
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
begin
  delete from public.guestbook
  where id = p_id
    and owner_token_hash = crypt(p_owner_token, owner_token_hash);

  return found;
end;
$$;

create or replace function public.is_guestbook_admin()
returns boolean
language sql
security definer
set search_path = public, extensions, pg_temp
as $$
  select exists (
    select 1
    from public.admin_users
    where admin_users.user_id = auth.uid()
  );
$$;

create or replace function public.admin_update_guestbook_entry(
  p_id bigint,
  p_name text,
  p_attendance text,
  p_message text
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
begin
  if not public.is_guestbook_admin() then
    return false;
  end if;

  if char_length(p_name) not between 1 and 20 then
    return false;
  end if;

  if p_attendance not in ('참석 예정', '불참', '미정') then
    return false;
  end if;

  if char_length(p_message) not between 1 and 300 then
    return false;
  end if;

  update public.guestbook
  set
    name = p_name,
    attendance = p_attendance,
    message = p_message
  where id = p_id;

  return found;
end;
$$;

create or replace function public.admin_delete_guestbook_entry(
  p_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
begin
  if not public.is_guestbook_admin() then
    return false;
  end if;

  delete from public.guestbook
  where id = p_id;

  return found;
end;
$$;

grant execute on function public.create_guestbook_entry(text, text, text, text) to anon, authenticated;
grant execute on function public.update_guestbook_entry(bigint, text, text, text, text) to anon, authenticated;
grant execute on function public.delete_guestbook_entry(bigint, text) to anon, authenticated;
grant execute on function public.list_guestbook_entries(text) to anon, authenticated;
grant execute on function public.is_guestbook_admin() to authenticated;
grant execute on function public.admin_update_guestbook_entry(bigint, text, text, text) to authenticated;
grant execute on function public.admin_delete_guestbook_entry(bigint) to authenticated;

-- 참석 의사 응답은 방명록과 분리해 저장합니다.
create table if not exists public.rsvp_responses (
  id bigint generated by default as identity primary key,
  side text not null,
  attendance text not null,
  name text not null,
  phone_last4 text not null,
  party_size integer not null default 1,
  note text not null default '',
  created_at timestamptz not null default now(),
  constraint rsvp_side_valid check (side in ('신랑', '신부')),
  constraint rsvp_attendance_valid check (attendance in ('참석', '불참')),
  constraint rsvp_name_length check (char_length(name) between 1 and 20),
  constraint rsvp_phone_last4_valid check (phone_last4 ~ '^[0-9]{4}$'),
  constraint rsvp_party_size_valid check (party_size between 1 and 5),
  constraint rsvp_note_length check (char_length(note) <= 100)
);

alter table public.rsvp_responses enable row level security;

drop policy if exists "Admins can read RSVP responses" on public.rsvp_responses;
drop policy if exists "Admins can delete RSVP responses" on public.rsvp_responses;

create policy "Admins can read RSVP responses"
on public.rsvp_responses
for select
to authenticated
using (public.is_guestbook_admin());

create policy "Admins can delete RSVP responses"
on public.rsvp_responses
for delete
to authenticated
using (public.is_guestbook_admin());

create index if not exists rsvp_responses_created_at_idx
on public.rsvp_responses (created_at desc);

create or replace function public.submit_rsvp_response(
  p_side text,
  p_attendance text,
  p_name text,
  p_phone_last4 text,
  p_party_size integer,
  p_note text
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  new_id bigint;
  clean_name text := trim(coalesce(p_name, ''));
  clean_note text := trim(coalesce(p_note, ''));
begin
  if p_side not in ('신랑', '신부') then
    raise exception 'invalid side';
  end if;

  if p_attendance not in ('참석', '불참') then
    raise exception 'invalid attendance';
  end if;

  if char_length(clean_name) not between 1 and 20 then
    raise exception 'invalid name';
  end if;

  if p_phone_last4 is null or p_phone_last4 !~ '^[0-9]{4}$' then
    raise exception 'invalid phone';
  end if;

  if p_party_size is null or p_party_size not between 1 and 5 then
    raise exception 'invalid party size';
  end if;

  if char_length(clean_note) > 100 then
    raise exception 'invalid note';
  end if;

  insert into public.rsvp_responses (side, attendance, name, phone_last4, party_size, note)
  values (p_side, p_attendance, clean_name, p_phone_last4, p_party_size, clean_note)
  returning id into new_id;

  return new_id;
end;
$$;

create or replace function public.admin_delete_rsvp_response(p_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.is_guestbook_admin() then
    return false;
  end if;

  delete from public.rsvp_responses where id = p_id;
  return found;
end;
$$;

grant execute on function public.submit_rsvp_response(text, text, text, text, integer, text) to anon, authenticated;
grant execute on function public.admin_delete_rsvp_response(bigint) to authenticated;

-- 관리자 설정:
-- 1. Supabase Dashboard > Authentication > Users에서 관리자 이메일/비밀번호 계정을 만듭니다.
-- 2. 생성된 User UID와 이메일을 아래 SQL에 넣어 한 번 실행합니다.
--
-- insert into public.admin_users (user_id, email)
-- values ('USER_UID_HERE', 'admin@example.com')
-- on conflict (user_id) do update set email = excluded.email;

-- 새 테이블과 RPC 함수가 PostgREST에 즉시 반영되도록 스키마 캐시를 갱신합니다.
notify pgrst, 'reload schema';
