create table if not exists public.guestbook (
  id bigint generated by default as identity primary key,
  name text not null,
  attendance text not null default '참석 예정',
  message text not null,
  created_at timestamptz not null default now()
);

do $$
declare
  constraint_record record;
begin
  for constraint_record in
    select conname
    from pg_constraint
    where conrelid = 'public.guestbook'::regclass
      and contype = 'c'
  loop
    execute format('alter table public.guestbook drop constraint if exists %I', constraint_record.conname);
  end loop;
end $$;

alter table public.guestbook
  add constraint guestbook_name_length check (char_length(name) between 1 and 20),
  add constraint guestbook_attendance_valid check (attendance in ('참석 예정', '불참', '미정')),
  add constraint guestbook_message_length check (char_length(message) between 1 and 300);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  created_at timestamptz not null default now()
);

alter table public.guestbook enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists "Anyone can read guestbook" on public.guestbook;
drop policy if exists "Anyone can write guestbook" on public.guestbook;
drop policy if exists "Admins can update guestbook" on public.guestbook;
drop policy if exists "Admins can delete guestbook" on public.guestbook;
drop policy if exists "Admins can read admin users" on public.admin_users;

create policy "Anyone can read guestbook"
on public.guestbook
for select
to anon, authenticated
using (true);

create policy "Anyone can write guestbook"
on public.guestbook
for insert
to anon
with check (
  char_length(name) between 1 and 20
  and attendance in ('참석 예정', '불참', '미정')
  and char_length(message) between 1 and 300
);

create policy "Admins can update guestbook"
on public.guestbook
for update
to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = auth.uid()
  )
  and char_length(name) between 1 and 20
  and attendance in ('참석 예정', '불참', '미정')
  and char_length(message) between 1 and 300
);

create policy "Admins can delete guestbook"
on public.guestbook
for delete
to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

create policy "Admins can read admin users"
on public.admin_users
for select
to authenticated
using (user_id = auth.uid());

create index if not exists guestbook_created_at_idx
on public.guestbook (created_at desc);

-- 관리자 설정:
-- 1. Supabase Dashboard > Authentication > Users에서 관리자 이메일/비밀번호 계정을 만듭니다.
-- 2. 생성된 User UID와 이메일을 아래 SQL에 넣어 한 번 실행합니다.
--
-- insert into public.admin_users (user_id, email)
-- values ('USER_UID_HERE', 'admin@example.com')
-- on conflict (user_id) do update set email = excluded.email;
